### ISSUE TITLE
compatibility with kcp-go

### ISSUE THREAD

**Issue by angelskieglazki** [miwarnec/kcp2k#53]
Is this code compatible with kcp-go?

**Comment by miwarnec** [comment]
Haven't checked kcp-go, but it is compatible with kcp except for a few bug fixes we applied!

**Comment by miwarnec** [comment]
to be clear, kcp.cs itself should be compatible.
our high level server/client abstractions aren't since they aren't officially part of kcp, we made them ourselves.
